/**
 * Launch-crash guardrails.
 *
 * The Google Mobile Ads SDK shipped to TestFlight twice (builds 134 and 136)
 * and crashed the app on launch in both cases — the SDK's
 * `GADApplicationVerifyPublisherInitializedCorrectly` check throws an
 * NSException from a libdispatch background block any time the framework is
 * linked into the binary but `[GADMobileAds.sharedInstance startWith…]` is
 * never called. Even after the JS layer was disabled, the SDK linkage alone
 * was enough to crash. PR #523 → PR #527 → PR #528 → PR #529 was the saga of
 * trying to keep the SDK linked-but-dormant, then giving up and removing it
 * entirely.
 *
 * These tests are the brick wall preventing that class of crash from
 * regressing: any reintroduction of AdMob or ATT plumbing — a stray
 * `npm install`, a manual `Info.plist` edit, an autogenerated Capacitor
 * sync — fails CI before it can ship.
 *
 * Scope: only checks for the specific AdMob/GMA/ATT surface, not all native
 * SDKs. Re-enabling ads in a future build is fine — at that point this file
 * gets rewritten to assert the SDK is linked AND properly initialized at
 * startup (the missing piece in the original crash).
 */

import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync, readdirSync } from 'fs';
import { resolve } from 'path';

const REPO_ROOT = resolve(__dirname, '..', '..');

function read(rel: string): string {
  return readFileSync(resolve(REPO_ROOT, rel), 'utf8');
}

describe('launch-crash guardrails — AdMob / GMA SDK must not regress into the iOS binary', () => {
  describe('package manifest', () => {
    it('package.json has no @capacitor-community/admob dependency', () => {
      const pkg = JSON.parse(read('package.json'));
      const allDeps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
      expect(allDeps['@capacitor-community/admob']).toBeUndefined();
    });

    it('package-lock.json has no admob entries', () => {
      const lock = read('package-lock.json');
      expect(lock).not.toMatch(/@capacitor-community\/admob/);
    });
  });

  describe('iOS native config', () => {
    const PLIST_PATH = 'ios/App/App/Info.plist';

    it('Info.plist has no GADApplicationIdentifier (would link GMA SDK on launch)', () => {
      const plist = read(PLIST_PATH);
      expect(plist).not.toMatch(/GADApplicationIdentifier/);
    });

    it('Info.plist has no NSUserTrackingUsageDescription (no ATT-using SDK linked)', () => {
      const plist = read(PLIST_PATH);
      expect(plist).not.toMatch(/NSUserTrackingUsageDescription/);
    });

    it('Info.plist has no SKAdNetworkItems (no ad-attribution SDK linked)', () => {
      const plist = read(PLIST_PATH);
      expect(plist).not.toMatch(/SKAdNetworkItems/);
    });

    it('Package.swift has no AdMob package reference (catches `cap sync` regressing it)', () => {
      const pkgSwift = read('ios/App/CapApp-SPM/Package.swift');
      expect(pkgSwift).not.toMatch(/CapacitorCommunityAdmob/);
      expect(pkgSwift).not.toMatch(/@capacitor-community\/admob/);
    });

    it('No localized InfoPlist.strings translates an ad-tracking purpose string', () => {
      const lprojRoot = resolve(REPO_ROOT, 'ios/App/App');
      if (!existsSync(lprojRoot)) return;
      for (const entry of readdirSync(lprojRoot)) {
        if (!entry.endsWith('.lproj')) continue;
        const stringsPath = resolve(lprojRoot, entry, 'InfoPlist.strings');
        if (!existsSync(stringsPath)) continue;
        const contents = readFileSync(stringsPath, 'utf8');
        expect(contents, `${entry}/InfoPlist.strings`).not.toMatch(/NSUserTrackingUsageDescription/);
      }
    });
  });

  describe('Android native config', () => {
    it('capacitor.settings.gradle does not include the AdMob plugin project', () => {
      const settings = read('android/capacitor.settings.gradle');
      expect(settings).not.toMatch(/capacitor-community-admob/);
    });

    it('app/capacitor.build.gradle does not depend on the AdMob plugin', () => {
      const build = read('android/app/capacitor.build.gradle');
      expect(build).not.toMatch(/capacitor-community-admob/);
    });
  });

  describe('source code', () => {
    it('No source file imports @capacitor-community/admob', () => {
      const offenders: string[] = [];
      function walk(dir: string) {
        for (const entry of readdirSync(dir, { withFileTypes: true })) {
          const full = resolve(dir, entry.name);
          if (entry.isDirectory()) {
            if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
            walk(full);
          } else if (/\.(ts|tsx|js|jsx)$/.test(entry.name)) {
            const text = readFileSync(full, 'utf8');
            // Match real imports/requires only — docblock mentions are fine.
            if (
              /from ['"]@capacitor-community\/admob['"]/.test(text) ||
              /require\(['"]@capacitor-community\/admob['"]\)/.test(text) ||
              /import\(['"]@capacitor-community\/admob['"]\)/.test(text)
            ) {
              offenders.push(full.replace(REPO_ROOT + '/', ''));
            }
          }
        }
      }
      walk(resolve(REPO_ROOT, 'src'));
      expect(offenders).toEqual([]);
    });
  });

  describe('ads.ts stub behavior', () => {
    it('NATIVE_ADS_READY is false (every callsite must short-circuit)', async () => {
      const { NATIVE_ADS_READY } = await import('@/utils/ads');
      expect(NATIVE_ADS_READY).toBe(false);
    });

    it('REWARDED_ADS_USABLE is false while showRewardedAd is a stub', async () => {
      // The reward UI gates on REWARDED_ADS_USABLE, not NATIVE_ADS_READY.
      // AdRewardButton grants Pro users their reward instantly (they skip the
      // ad) and routes free users through showRewardedAd(). If the plugin flag
      // were flipped while this file still returned false, Pro would collect
      // every budget reward and free users none — a Pro-only economic buff and
      // a breach of the "monetization never touches sim parameters" contract.
      // This test pins the two flags together so one cannot be flipped alone.
      const { REWARDED_ADS_USABLE, showRewardedAd } = await import('@/utils/ads');
      expect(REWARDED_ADS_USABLE).toBe(false);
      await expect(showRewardedAd()).resolves.toBe(false);
    });

    it('no reward surface gates on NATIVE_ADS_READY directly', async () => {
      // Callsites must use the derived REWARDED_ADS_USABLE so that enabling the
      // plugin cannot open a reward path against a stub implementation.
      const offenders: string[] = [];
      for (const rel of ['src/components/game/AdRewardButton.tsx', 'src/pages/PacksPage.tsx']) {
        const src = readFileSync(resolve(REPO_ROOT, rel), 'utf8');
        if (/\bNATIVE_ADS_READY\b/.test(src.replace(/\/\/[^\n]*/g, ''))) offenders.push(rel);
      }
      expect(offenders).toEqual([]);
    });

    it('initAds() resolves without throwing', async () => {
      const { initAds } = await import('@/utils/ads');
      await expect(initAds()).resolves.toBeUndefined();
    });

    it('showRewardedAd() resolves false (never grants a reward when ads are off)', async () => {
      const { showRewardedAd } = await import('@/utils/ads');
      await expect(showRewardedAd()).resolves.toBe(false);
    });
  });
});
