/* eslint-disable no-console -- diagnostic stats reporting */
/**
 * Squad-route report — does buying packs outpace playing football?
 *
 * The design brief's standing worry is that Dynasty Manager degenerates into
 * "open pack → sell → open pack", with the football underneath it reduced to
 * scenery. That is a real risk and it is NOT a question anyone should answer
 * from intuition, so this measures it instead of guessing.
 *
 * The question, made concrete: for the SAME club, how much squad strength
 * arrives per route?
 *
 *   PACKS     — what a tier deals, and how much of it actually beats the XI
 *               you already have.
 *   TRANSFERS — what the club's own budget buys at market prices.
 *
 * "Squad strength" is measured two ways on purpose, because they disagree and
 * the disagreement is the interesting part:
 *
 *   BOOK VALUE  — the market price of what the pack dealt. Flatters packs:
 *                 five 78s look like a fortune and may not improve the team
 *                 at all.
 *   XI UPGRADES — cards that out-rate the club's current best in that
 *                 position. This is the honest one. A card that does not
 *                 crack the XI has not built anything.
 *
 * Gated behind VITEST_ROUTES=1 so normal runs don't pay the cost:
 *
 *   VITEST_ROUTES=1 npx vitest run squadRouteReport
 *
 * A REPORT, not a gate. It asserts only that the markdown was written — the
 * numbers are for a human to read before touching a single balance value.
 */
import { describe, it, expect } from 'vitest';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import type { Player } from '@/types/game';
import { useGameStore } from '@/store/gameStore';
import { generatePackContents } from '@/utils/packGeneration';
import { PACK_STOREFRONT_ORDER, PACK_TIER_MAP } from '@/config/packs';
import type { PackTierKey } from '@/types/game';

const RUN = process.env.VITEST_ROUTES === '1';
const SAMPLES = 200;

/** Clubs spanning the money range, so the answer isn't only true for a giant. */
const REFERENCE_CLUBS = [
  { id: 'manchester-city', label: 'Elite' },
  { id: 'celtic', label: 'Mid' },
  { id: 'luton-town', label: 'Lower' },
];

const money = (n: number) => `£${(n / 1_000_000).toFixed(1)}M`;
const mean = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0);
function median(xs: number[]): number {
  if (!xs.length) return 0;
  const s = [...xs].sort((a, b) => a - b);
  const m = Math.floor(s.length / 2);
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
}

/** Best overall per position in a squad — the bar a pull has to clear. */
function bestByPosition(playerIds: string[], all: Record<string, Player>): Map<string, number> {
  const best = new Map<string, number>();
  for (const id of playerIds) {
    const p = all[id];
    if (!p) continue;
    if (p.overall > (best.get(p.position) ?? 0)) best.set(p.position, p.overall);
  }
  return best;
}

/** Cards that would displace the current best in their position. Mirrors
 *  `computeSquadImprovement` in PacksPage — same definition the reveal screen
 *  uses to badge an upgrade, so the report and the game agree on the word. */
function countXiUpgrades(pulled: Player[], best: Map<string, number>): number {
  let n = 0;
  for (const p of pulled) {
    const bar = best.get(p.position) ?? 0;
    if (bar > 0 && p.overall > bar) n += 1;
  }
  return n;
}

describe('squad-route report', () => {
  it.skipIf(!RUN)('measures packs against the club\'s own budget', () => {
    const lines: string[] = [];
    lines.push('# Squad routes — packs vs football');
    lines.push('');
    lines.push(`Generated by \`src/test/squadRouteReport.test.ts\` · ${SAMPLES} opens per tier per club.`);
    lines.push('');
    lines.push('**Read XI upgrades, not book value.** Book value is what the cards are');
    lines.push('worth; XI upgrades are what they actually change. A pack that deals');
    lines.push('£40M of players who all sit on the bench has built nothing.');
    lines.push('');

    for (const club of REFERENCE_CLUBS) {
      useGameStore.getState().initGame(club.id);
      const state = useGameStore.getState();
      const clubData = state.clubs[state.playerClubId];
      if (!clubData) continue;

      const squad = clubData.playerIds.map(id => state.players[id]).filter(Boolean) as Player[];
      const best = bestByPosition(clubData.playerIds, state.players);
      const xi = [...squad].sort((a, b) => b.overall - a.overall).slice(0, 11);
      const xiAvg = mean(xi.map(p => p.overall));
      const budget = clubData.budget;

      lines.push(`## ${clubData.name} (${club.label})`);
      lines.push('');
      lines.push(`- Transfer budget: **${money(budget)}**`);
      lines.push(`- Best XI average: **${xiAvg.toFixed(1)} OVR**`);
      lines.push(`- Squad size: ${squad.length}`);
      lines.push('');
      lines.push('| Pack | $ | Cards | Best OVR (med) | Book value | Book per $ | XI upgrades | Cost of 1 upgrade |');
      lines.push('|---|---:|---:|---:|---:|---:|---:|---:|');

      for (const tierKey of PACK_STOREFRONT_ORDER) {
        const tier = PACK_TIER_MAP[tierKey];
        if (!tier) continue;
        // `iapPriceDisplay` is the planned tier ('$4.99'); the real price comes
        // from the store at runtime, so this is a planning figure, not a fact.
        const price = usdOf(tier.iapPriceDisplay);

        const bestOvrs: number[] = [];
        const books: number[] = [];
        const upgrades: number[] = [];

        for (let i = 0; i < SAMPLES; i++) {
          const pulled = generatePackContents(tierKey, state.season, {
            freeOpen: price === 0,
            streak: 1,
          });
          if (!pulled.length) continue;
          bestOvrs.push(Math.max(...pulled.map(p => p.overall)));
          books.push(pulled.reduce((s, p) => s + (p.value || 0), 0));
          upgrades.push(countXiUpgrades(pulled, best));
        }

        const avgUpgrades = mean(upgrades);
        // The number that matters commercially AND for game health: what does
        // it cost to actually improve the team by one player?
        const costPerUpgrade = avgUpgrades > 0 && price > 0
          ? `$${(price / avgUpgrades).toFixed(2)}`
          : avgUpgrades > 0 ? 'free' : '—';

        lines.push(
          `| ${tier.label} | ${price ? `$${price.toFixed(2)}` : 'free'} | ${pulledCount(tierKey)} `
          + `| ${median(bestOvrs).toFixed(0)} `
          + `| ${money(mean(books))} `
          + `| ${price ? money(mean(books) / price) : '—'} `
          + `| ${avgUpgrades.toFixed(2)} `
          + `| ${costPerUpgrade} |`,
        );
      }

      lines.push('');
      // The headline comparison: one pack's book value against the entire
      // budget the football game gives you for the season.
      const goldBook = sampleBook('gold', state.season);
      lines.push(`One Champions pack ($2.99) deals ${money(goldBook)} of book value — `
        + `**${((goldBook / Math.max(1, budget)) * 100).toFixed(0)}%** of this club's whole transfer budget.`);
      lines.push('');
    }

    lines.push('## How to read this');
    lines.push('');
    lines.push('**Accepted design (2026-09-06).** Packs out-building the football is a');
    lines.push('known, measured and DELIBERATE property of this game, not a defect');
    lines.push('awaiting a fix. The product decision is that Dynasty Manager sells squad');
    lines.push('strength. This report exists to keep that effect measured and bounded,');
    lines.push('not to argue against it — see the ratchet in the same file, and the');
    lines.push('release-scope note in CLAUDE.md.');
    lines.push('');
    lines.push('- **XI upgrades** is the honest measure of what a pack buys. It is high');
    lines.push('  for lower clubs by design: an absolute guaranteed floor is worth more');
    lines.push('  the weaker your squad. Watch it for DRIFT, not for the level.');
    lines.push('- If **book value per $** dwarfs the season budget but **XI upgrades**');
    lines.push('  stays near zero, packs are selling cash rather than strength — that');
    lines.push('  one IS still a problem, and the quick-sell taper governs it.');
    lines.push('- **Price-ladder check.** Compare `cost of 1 upgrade` down each club\'s');
    lines.push('  column. If the cheapest pack is the best value at every club, the');
    lines.push('  ladder is inverted and the expensive tiers are hard to justify to a');
    lines.push('  paying player. That is a revenue question, not a fairness one.');
    lines.push('');

    const out = join(process.cwd(), 'docs', 'squad-routes-report.md');
    if (!existsSync(dirname(out))) mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, lines.join('\n'), 'utf-8');
    console.log(`\n${lines.join('\n')}\n`);
    expect(existsSync(out)).toBe(true);
  }, 120_000);
});

/** Card count a tier deals, for the table. */
function pulledCount(tierKey: PackTierKey): number {
  return PACK_TIER_MAP[tierKey]?.cards ?? 0;
}

/** Parse the planned USD tier off `iapPriceDisplay`. Free tiers have none. */
function usdOf(display: string | undefined): number {
  if (!display) return 0;
  const n = Number(display.replace(/[^0-9.]/g, ''));
  return Number.isFinite(n) ? n : 0;
}

/** Mean book value of one tier's open, sampled independently for the headline. */
function sampleBook(tierKey: PackTierKey, season: number): number {
  const books: number[] = [];
  for (let i = 0; i < SAMPLES; i++) {
    const pulled = generatePackContents(tierKey, season, {});
    books.push(pulled.reduce((s, p) => s + (p.value || 0), 0));
  }
  return mean(books);
}

/**
 * Regression ratchet on the measured pack-vs-football problem.
 *
 * A CEILING ON AN ACCEPTED DESIGN, not a placeholder for a fix.
 *
 * Measured: a single $2.99 Champions pack replaces ~3.3 of a lower-league
 * club's starting XI — six times that club's entire transfer budget, about
 * $0.90 per XI upgrade — while the same pack is correctly-tuned filler at
 * Manchester City. An absolute guaranteed floor (78+) is worth more the
 * weaker your squad, so the effect is strongest where the club is poorest.
 *
 * The product decision (2026-09-06) is to ACCEPT this: Dynasty Manager sells
 * squad strength, and pay-to-win is the intended model. Four alternatives
 * were on the table — scaling floors to squad level, tiering the storefront
 * by division, weakening cheap floors, or accepting it — and acceptance was
 * chosen deliberately with these numbers in hand. See CLAUDE.md.
 *
 * So this test does not argue the level. It bounds the DRIFT. A raised
 * guaranteed floor, a bigger version boost or a cheaper elite band could push
 * this well past what was actually agreed, and nobody would notice without a
 * number watching it.
 *
 * Bound sizing: measured mean 3.31 XI upgrades, sd 1.05. At n=150 the
 * standard error is 0.086, putting 6 sigma at 3.81, so 4.0 cannot false-fail
 * on sampling noise but catches real movement.
 *
 * If this fails, do not simply raise the bound — that is how an accepted
 * position becomes an unexamined one. Re-run the report, confirm the new
 * level is what the owner wants, and move the bound as a decision.
 */
describe('pack supply — the lower-league ratchet', () => {
  const RUNS = 150;
  /** Chosen because it is the worst case in the report: the poorest squad
   *  measured, where an absolute guaranteed floor does the most damage. */
  const CLUB_ID = 'luton-town';
  const MAX_XI_UPGRADES = 4.0;

  it('a $2.99 pack rebuilds no more of a lower-league XI than the accepted level', () => {
    useGameStore.getState().initGame(CLUB_ID);
    const state = useGameStore.getState();
    const club = state.clubs[state.playerClubId];
    const best = bestByPosition(club.playerIds, state.players);

    let total = 0;
    for (let i = 0; i < RUNS; i++) {
      total += countXiUpgrades(generatePackContents('gold', state.season, {}), best);
    }
    const avg = total / RUNS;

    expect(
      avg,
      `Champions pack now replaces ${avg.toFixed(2)} of ${club.name}'s XI (was ~3.3). `
      + 'Packs got stronger or lower-league squads got weaker. Pay-to-win is accepted; '
      + 'unexamined drift past the agreed level is not. Re-measure before moving this.',
    ).toBeLessThan(MAX_XI_UPGRADES);
  }, 60_000);
});
