language: en-US
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  path_filters:
    - "!src/components/ui/**"
    - "!dist/**"
    - "!package-lock.json"
  pre_merge_checks:
    docstrings:
      mode: "off"
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
