#!/usr/bin/env node
/** Write marketing/content/videos.md from videos.mjs and what is on disk.
 *  node marketing/postproduction/videos-md.mjs */
import { writeFileSync, existsSync, statSync } from 'fs';
import { join } from 'path';
import { VIDEOS } from '../content/videos.mjs';

const dir = join(process.cwd(), 'marketing', 'content', 'videos');
const rows = VIDEOS.map(v => {
  const f = join(dir, `${v.id}-ios.mp4`);
  const ok = existsSync(f);
  const mb = ok ? (statSync(f).size / 1e6).toFixed(1) : '—';
  return `| ${v.day ?? 'pilot'} | \`${v.id}\` | ${ok ? '✅' : '❌ not rendered'} | ${mb} | ${v.post.replace(/\|/g, '\\|')} |`;
});
writeFileSync(join(process.cwd(), 'marketing', 'content', 'videos.md'), `# Rendered videos

Generated by \`node marketing/postproduction/videos-md.mjs\` from \`videos.mjs\`.
Files live in \`marketing/content/videos/\` (gitignored — regenerate with
\`node marketing/postproduction/render-calendar.mjs\`). Each id has two files:

- \`<id>-ios.mp4\` — end card "Free on iPhone". **Post these now.**
- \`<id>-android.mp4\` — end card "Free on iPhone & Android". **Only after the
  Play listing is public** (PLAYBOOK §13.1).

All are 1080×1920, 60 fps, H.264 + AAC, with a synthesised score (no music
licence involved). Add a trending sound in-app only from TikTok's Commercial
Music Library if you want one; mute the built-in track first.

Before posting any video, watch it once: Road to Glory, Sunday League and the
pilots caption what the engine actually did in that render.

| Day | Id | Status | MB | Post caption |
|---|---|---|---|---|
${rows.join('\n')}
`);
console.log(`videos.md: ${rows.length} rows`);
