#!/usr/bin/env node
/**
 * Phase 10 — diff the FC27 dataset against the baseline already in the repo.
 *
 * Two baselines ship here, in different schemas:
 *   - `FC26_20250921.csv`  SoFIFA-shaped (player_id, overall, potential, dob…)
 *   - `fc25_players.csv`   EA-ratings-shaped (Name, OVR, Team…, url ending /<id>)
 *
 * Both carry the same persistent player id — SoFIFA's `player_id` and the
 * trailing segment of an EA ratings URL are one id space — so id matching is
 * tried first. It is not assumed to work: every pair records the tier it
 * matched on and the report prints the histogram, so a collapsed id space is
 * visible rather than silently degrading into name matching.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { toCsv } from './lib/csv.mjs';
import { readComparable, matchPlayers, normName } from './lib/players.mjs';
import { parseArgs } from './lib/args.mjs';
import { BASELINES, COMPARISON_DIR, COMPARISON_REPORT_PATH, MALE_CSV } from './lib/paths.mjs';

/** Column sets for the emitted diff files, so their headers stay stable. */
const COLUMNS = {
  roster: ['id', 'name', 'club', 'league', 'position', 'overall'],
  ratings: ['player_id', 'name', 'match_tier', 'overall_before', 'overall_after', 'delta'],
  potential: ['player_id', 'name', 'match_tier', 'potential_before', 'potential_after', 'delta'],
  clubs: ['player_id', 'name', 'match_tier', 'club_before', 'club_after', 'league_before', 'league_after'],
  positions: ['player_id', 'name', 'match_tier', 'position_before', 'position_after'],
};

const readFile = (path) => readComparable(readFileSync(path, 'utf8'));

/** Pairs where a numeric field is present on both sides and differs. */
const changedNumeric = (pairs, field) => pairs
  .filter((p) => p.current[field] !== null && p.base[field] !== null && p.current[field] !== p.base[field])
  .map((p) => ({
    player_id: p.current.id,
    name: p.current.name,
    match_tier: p.tier,
    [`${field}_before`]: p.base[field],
    [`${field}_after`]: p.current[field],
    delta: p.current[field] - p.base[field],
  }))
  .sort((a, b) => b.delta - a.delta);

export function run({
  csvPath = MALE_CSV,
  baselineKey = 'fc26',
  outDir = COMPARISON_DIR,
  reportPath = COMPARISON_REPORT_PATH,
} = {}) {
  const baselinePath = BASELINES[baselineKey] ?? baselineKey;
  if (!existsSync(csvPath)) throw new Error(`No FC27 dataset at ${csvPath}.`);
  if (!existsSync(baselinePath)) throw new Error(`No baseline at ${baselinePath}.`);

  const current = readFile(csvPath);
  const baseline = readFile(baselinePath);
  const { pairs, newPlayers, removed, tiers } = matchPlayers(current, baseline);

  const changedRatings = changedNumeric(pairs, 'overall');
  const changedPotential = changedNumeric(pairs, 'potential');
  const changedClubs = pairs
    .filter((p) => normName(p.current.club) !== normName(p.base.club))
    .map((p) => ({
      player_id: p.current.id, name: p.current.name, match_tier: p.tier,
      club_before: p.base.club, club_after: p.current.club,
      league_before: p.base.league, league_after: p.current.league,
    }));
  const changedPositions = pairs
    .filter((p) => p.current.position && p.base.position && p.current.position !== p.base.position)
    .map((p) => ({
      player_id: p.current.id, name: p.current.name, match_tier: p.tier,
      position_before: p.base.position, position_after: p.current.position,
    }));

  mkdirSync(outDir, { recursive: true });
  const dump = (name, columns, rows) => {
    writeFileSync(join(outDir, `${name}.csv`), toCsv(columns, rows), 'utf8');
    return rows.length;
  };

  const counts = {
    new_players: dump('new_players', COLUMNS.roster, newPlayers),
    removed_players: dump('removed_players', COLUMNS.roster, removed),
    changed_ratings: dump('changed_ratings', COLUMNS.ratings, changedRatings),
    changed_potential: dump('changed_potential', COLUMNS.potential, changedPotential),
    changed_clubs: dump('changed_clubs', COLUMNS.clubs, changedClubs),
    changed_positions: dump('changed_positions', COLUMNS.positions, changedPositions),
  };

  const movers = (rows) => rows.map((r) => `| ${r.name} | ${r.overall_before} | ${r.overall_after} | ${r.delta > 0 ? '+' : ''}${r.delta} |`);
  const report = [
    `# ${baselineKey.toUpperCase()} vs FC27`,
    '',
    `> Generated by \`scripts/fc27/compare_fc25.mjs\` on ${new Date().toISOString()}.`,
    `> Baseline: \`${baselinePath}\` · Current: \`${csvPath}\``,
    '',
    '## Match quality',
    '',
    '| Tier | Pairs |',
    '| --- | ---: |',
    ...Object.entries(tiers).map(([t, c]) => `| ${t} | ${c} |`),
    `| **unmatched (treated as new)** | ${newPlayers.length} |`,
    '',
    'A healthy run matches the overwhelming majority on `id`. Heavy reliance on',
    'the name tiers means the two id spaces do not line up, and the diff below',
    'should then be read as indicative rather than exact.',
    '',
    '## Changes',
    '',
    '| Set | Rows | File |',
    '| --- | ---: | --- |',
    ...Object.entries(counts).map(([k, v]) => `| ${k.replaceAll('_', ' ')} | ${v} | \`${k}.csv\` |`),
    '',
    '## Biggest rating movers',
    '',
    '| Player | Before | After | Δ |',
    '| --- | ---: | ---: | ---: |',
    ...movers(changedRatings.slice(0, 15)),
    ...movers(changedRatings.slice(-15).reverse()),
    '',
  ].join('\n');

  mkdirSync(dirname(reportPath), { recursive: true });
  writeFileSync(reportPath, `${report}\n`, 'utf8');

  return { counts, tiers, reportPath, matched: pairs.length };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = parseArgs(process.argv.slice(2));
  const result = run({
    csvPath: args.csv,
    baselineKey: args.baseline ?? 'fc26',
    outDir: args.outDir,
    reportPath: args.report,
  });
  console.log(`[compare] matched ${result.matched}; tiers=${JSON.stringify(result.tiers)}`);
  console.log(`[compare] ${JSON.stringify(result.counts)} -> ${result.reportPath}`);
}
